name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        tag=$(date +%s)
        echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u cbruegg --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/cbruegg/social-media-center:$tag
        docker push ghcr.io/cbruegg/social-media-center:$tag
